### ISSUE TITLE
Some classes implement IDisposableObservable, but there is no reference to Microsoft.VisualStudio.Validation

### ISSUE THREAD

**Issue by qmfrederik** [AArnott/Nerdbank.Streams#336]
Some classes, such as `SimplexStream`, implement the `IDisposableObservable` interface. This interface is defined in `Microsoft.VisualStudio.Validation`, but the NerdBank.Streams package dropped its (declared) dependency on `Microsoft.VisualStudio.Validation` in the 2.7 series.

Wouldn't it be better NerdBank.Streams to add a package reference to Microsoft.VisualStudio.Validation if it exposes interfaces from that type?

**Comment by AArnott** [comment]
A nuget dependency on Microsoft.VisualStudio.Validation still exists, *transitively* through its direct dependency on Microsoft.VisualStudio.Threading. The way the tooling works, there is no added benefit (and some negative) to adding redundant direct dependencies.

**Comment by qmfrederik** [comment]
Thats not correct. Consider the following `.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nerdbank.Streams" Version="2.7.74" />
  </ItemGroup>

</Project>
```

and this code file:

```csharp
using Microsoft;
using Nerdbank.Streams;

public class Project
{
    public static void Main()
    {
        IDisposableObservable d = new SimplexStream();
    }
}
```

This will result in a compiler error:

```
error CS0246: The type or namespace name 'IDisposableObservable' could not be found (are you missing a using directive or an assembly reference?)
```

when using 2.7.74; the code compiles with version 2.6.81

**Comment by AArnott** [comment]
It should work. Maybe there's an `exclude="compile"` somewhere.

**Comment by qmfrederik** [comment]
Yeah, probably:

In `src/Nerdbank.Streams/Nerdbank.Streams.csproj`:

```xml
    <PackageReference Include="Microsoft.VisualStudio.Threading" Version="16.9.60" PrivateAssets="build;analyzers;compile" />
```

**Comment by AArnott** [comment]
Fixed. Thanks.

**Comment by AArnott** [comment]
I chose not to fix it by removing `compile` from the list on the threading reference because I am intentionally trying to not bring in the whole threading library to the consumers project just because they want some streaming functions.

**Comment by qmfrederik** [comment]
Thanks, @AArnott .
